@urlLocal = http://localhost:8000/api

### Obtener listado de Users
GET {{urlLocal}}/users

### Obtener un User
GET {{urlLocal}}/users/1

### Obtener un User con el nuevo DTO
GET {{urlLocal}}/users/newDto/1